spring:
  application:
    name: citafin-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:citafin}
    username: ${DB_USERNAME:citafin}
    password: ${DB_PASSWORD:citafin_local}
  docker:
    compose:
      enabled: ${SPRING_DOCKER_COMPOSE_ENABLED:true}
      file: ../../compose.yaml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    baseline-on-migrate: false
    locations: classpath:db/migration
    validate-migration-naming: true

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
